package net.igorkromin.jphotoframe;

/**
 * Listener interface for pause/resume events generated by the ImageDirectory watcher.
 * These events are called when the 'pause' file is detected/removed from the image directory.
 */
public interface PauseListener {

    void pauseEvent();
    void resumeEvent();

}
